full_columns = [
    "Education",
    "Race",
    "Gender",
    "Age",
    "Outreach Y/N",
    "In person",
    "Phone call",
    "Email or text message",
    "Letter or postcard",
    "State FIPS Code"
]


# Columns in CES Data to be renamed
[demographic_columns]
educ = "Education"
race = "Race"
hispanic = "Hispanic"
gender4 = "Gender"
birthyr = "Birth Year"

[voter_outreach_columns]
CC24_431a = "Outreach Y/N"
CC24_431b_1 = "In person"
CC24_431b_2 = "Phone call"
CC24_431b_3 = "Email or text message"
CC24_431b_4 = "Letter or postcard"

[state_column]
inputstate = "State FIPS Code"

[educ_mapping]
1 = "No HS degree"
2 = "High school graduate"
3 = "Some college, no degree (yet)"
4 = "2 year college degree"
5 = "4 year college degree"
6 = "Postgraduate degree"
8 = "Skipped"
9 = "Not asked"

[race_mapping]
1 = "White"
2 = "Black"
3 = "Hispanic"
4 = "Asian"
5 = "Native American"
6 = "Two or more races"
7 = "Other"
8 = "Middle Eastern"

[gender_mapping]
1 = "Man"
2 = "Woman"
3 = "Non-binary"
4 = "Other"

