
data_path = ".data"

full_columns = [
    "Education",
    "Race",
    "Gender",
    "Age",
    "In person",
    "Phone call",
    "Email or text message",
    "Letter or postcard",
    "State FIPS Code",
    "Voted"
]

categorical_features = [
    "Education",
    "Race",
    "Gender",
    "In person",
    "Phone call",
    "Email or text message",
    "Letter or postcard",
    "NCSL Classification"
]

multiclass_features = [
    "Education",
    "Race",
    "Gender",
    "NCSL Classification"
]

binary_features = [
    "In person",
    "Phone call",
    "Email or text message",
    "Letter or postcard",
]


features = [
    "Education",
    "Race",
    "Gender",
    "Age",
    "In person",
    "Phone call",
    "Email or text message",
    "Letter or postcard",
    "NCSL Classification"
]
target = "Voted"


# Columns in CES Data to be renamed
[demographic_columns]
educ = "Education"
race = "Race"
hispanic = "Hispanic"
gender4 = "Gender"
birthyr = "Birth Year"

[voter_outreach_columns]
CC24_431b_1 = "In person"
CC24_431b_2 = "Phone call"
CC24_431b_3 = "Email or text message"
CC24_431b_4 = "Letter or postcard"

[state_column]
inputstate = "State FIPS Code"

[maps]
"Education" = "educ_mapping"
"Race" = "race_mapping"
"Gender" = "gender_mapping"
"In person" = "in_person_mapping"
"Phone call" = "phone_mapping"
"Email or text message" = "email_mapping"
"Letter or postcard" = "letter_mapping"

[educ_mapping]
1 = "No HS degree"
2 = "High school graduate"
3 = "Some college, no degree (yet)"
4 = "2 year college degree"
5 = "4 year college degree"
6 = "Postgraduate degree"
8 = "Skipped"
9 = "Not asked"

[race_mapping]
1 = "White"
2 = "Black"
3 = "Hispanic"
4 = "Asian"
5 = "Native American"
6 = "Two or more races"
7 = "Other"
8 = "Middle Eastern"

[gender_mapping]
1 = "Man"
2 = "Woman"
3 = "Non-binary"
4 = "Other"

[in_person_mapping]
"1.0" = "Yes"
"2.0" = "No"

[phone_mapping]
"1.0" = "Yes"
"2.0" = "No"

[email_mapping]
"1.0" = "Yes"
"2.0" = "No"

[letter_mapping]
"1.0" = "Yes"
"2.0" = "No"


