[project]
name = "capstone-2026"
description = "Capstone project UMich MADS Spring/Summer 2026."
version = "1.0.0"
requires-python = ">= 3.13"
authors = [
  {name = "Andy Tunison", email = "andrew.e.tunison@gmail.com"},
  {name = "Yueyao Ren", email="yyren@umich.edu"},
  {name = "Sahana Sundar", email="sahanasu@umich.edu"}
]
readme = "README.md"
dependencies = [
  "matplotlib==3.10.9",
  "numpy==2.5.1",
  "pandas==3.0.3",
  "patsy==1.0.2",
  "requests==2.34.2",
  "scipy==1.18.0",
  "statsmodels==0.14.6",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/atunison3/capstone"
Documentation = "https://atunison3.github.io/capstone/#/"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
extend-exclude = ["mke_um_figs.py"]  # Excludes the notes (allows us to have unclean code there)

[[tool.mypy.overrides]]
module = [
  "statsmodels",
  "statsmodels.*"
]
ignore_missing_imports = true


[tool.setuptools]
packages = ["capstone"]

[project.scripts]
capstone = "capstone.analysis:main"
